services:
  mongodb:
    build: ./mongodb
    image: 200620009955/mongodb:1.0.0
    container_name: mongodb  
  catalogue:
    build: ./catalogue
    image: 200620009955/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: 200620009955/user:1.0.0.
    container_name: user
    depends_on:
      - mongodb
      - redis
  redis:
    image: redis:7
    container_name: redis
  cart: 
    build: ./cart
    image: 200620009955/cart:1.0.0
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    build: ./mysql
    image: 200620009955/mysql:1.0.0
    container_name: mysql
  shipping:
    build: ./shipping
    image: 200620009955/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    build: rabbitmq:3
    image: 200620009955/rabbitmq:1.0.0
    environment: 
      RABBITMQ_DEFAULT_USER: Rodoshop 
      RABBITMQ_DEFAULT_PASS: Roboshop123 
    container_name: rabbitmq

  payment:
    build: ./payment
    image: 200620009955/payment:1.0.0
    container_name: payment
    environment: 
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
      - rabbitmq
      - user
      - cart
  frontend: 
    build: ./frontend
    image: 200620009955/frontend:1.0.0
    container_name: frontend
    ports: 
      - "80:80"
    depends_on:
      - mongodb
      - catalogue
      - user
      - redis
      - cart
      - mysql
      - shipping
networks:
  default:
    driver: bridge
    name: roboshop
    external: false

    