services:
  mongodb:
    build: ./mongodb
    image: mongodb:1.0.0
    container_name: mongodb  
  catalogue:
    build: ./catalogue
    image: catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: user:1.0.0.
    container_name: user
    depends_on:
      - mongodb
      - redis
  redis:
    image: redis:7
    container_name: redis
  cart: 
    build: ./cart
    image: cart:1.0.0
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    build: ./mysql
    image: 200620009955/mysql:1.0.0
    container_name: mysql\
  shipping:
    build: ./shipping
    image: 200620009955/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart
  frontend: 
    build: ./frontend
    image: frontend:1.0.0
    container_name: frontend
    ports: 
      - "80:80"
    depends_on:
      - mongodb
      - catalogue
      - user
      - redis
      - cart
networks:
  default:
    driver: bridge
    name: roboshop
    external: false

    